language: cpp
sudo: false
addons:
  apt:
    packages:
      - pandoc
compiler:
  - gcc
  - clang
env:
  - CFLAGS=-O2 CXXFLAGS=-O2
  - CFLAGS="-O2 -pedantic -Wall -Wextra -Werror" CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror"
  - CFLAGS=-O3 CXXFLAGS=-O3
script: autoreconf -f -i && ./configure && make check
