language: cpp
sudo: false
branches:
  only:
    - staging
    - trying
addons:
  apt:
    packages:
      - pandoc
compiler:
  - gcc
  - clang
env:
  - CFLAGS=-O2 CXXFLAGS=-O2
  - CFLAGS="-O2 -pedantic -Wall -Wextra -Werror" CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror"
  - CFLAGS=-O3 CXXFLAGS=-O3
script: support/test-build.sh
