language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pandoc
compiler:
  - gcc
  - clang
env:
  - CFLAGS=-O2 CXXFLAGS=-O2
  - CFLAGS="-O2 -Wall -Wextra -Werror" CXXFLAGS="-O2 -Wall -Wextra -Werror"
  - CFLAGS=-O3 CXXFLAGS=-O3
script: autoreconf -f -i && ./configure && make
